# Generated by Django 5.1.1 on 2024-10-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
