# Generated by Django 5.1.1 on 2024-10-13 18:02

import django.db.models.deletion
from django.db import migrations, models

def make_initial_rows(apps, scheme_editor):
    state_names = [
        "DRAFT",
        "FORMED",
        "DELETED",
        "FINISHED",
        "DISMISSED",
    ]

    OrderState = apps.get_model('metroapp', 'OrderState')
    for id, name in enumerate(state_names):
        OrderState.objects.create(id=id, state=name)
    

class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0002_route_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='metroapp.orderstate'),
        ),
        migrations.RunPython(make_initial_rows),
    ]
