# Generated by Django 5.1.1 on 2024-11-17 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0005_alter_routeorder_order_alter_routeorder_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FORMED', 'Formed'), ('DELETED', 'Deleted'), ('FINISHED', 'Finished'), ('DISMISSED', 'Dismissed')], default='DRAFT', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=128)),
                ('formed_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.RemoveField(
            model_name='routeorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='routeorder',
            name='route',
        ),
        migrations.CreateModel(
            name='RouteTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metroapp.route')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metroapp.trip')),
            ],
            options={
                'unique_together': {('route', 'trip')},
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='RouteOrder',
        ),
    ]
