# Generated by Django 5.1.1 on 2024-10-26 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField()),
                ('created_at', models.DateTimeField()),
                ('owner', models.CharField(max_length=128)),
                ('formed_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=256)),
                ('destination', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('thumbnail', models.URLField(null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'routes',
                'constraints': [models.UniqueConstraint(fields=('origin', 'destination', 'description'), name='unique constraint')],
            },
        ),
        migrations.CreateModel(
            name='RouteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metroapp.order')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metroapp.route')),
            ],
        ),
    ]
