# Generated by Django 5.1.1 on 2024-10-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0002_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
