# Generated by Django 5.1.1 on 2024-10-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0003_alter_route_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='DRAFT', max_length=32),
        ),
    ]
