# Generated by Django 5.1.1 on 2024-10-26 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metroapp.order'),
        ),
        migrations.AlterField(
            model_name='routeorder',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metroapp.route'),
        ),
    ]
