# Generated by Django 5.1.1 on 2025-01-14 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0006_trip_remove_routeorder_order_remove_routeorder_route_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='routetrip',
            options={'verbose_name': 'Маршрут поездки', 'verbose_name_plural': 'Маршруты поездок'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.RemoveConstraint(
            model_name='route',
            name='unique constraint',
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(max_length=256, verbose_name='Пункт назначения'),
        ),
        migrations.AlterField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный маршрут'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.CharField(max_length=256, verbose_name='Пункт отправления'),
        ),
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='route',
            name='thumbnail',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='routetrip',
            name='free',
            field=models.BooleanField(default=False, verbose_name='Бесплатно'),
        ),
        migrations.AlterField(
            model_name='routetrip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metroapp.route', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='routetrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metroapp.trip', verbose_name='Поездка'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ended_at',
            field=models.DateTimeField(null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='formed_at',
            field=models.DateTimeField(null=True, verbose_name='Дата формирования'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='owner',
            field=models.CharField(max_length=128, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('FORMED', 'Сформирован'), ('DELETED', 'Удален'), ('FINISHED', 'Завершен'), ('DISMISSED', 'Отменен')], default='DRAFT', max_length=32, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('origin', 'destination', 'description'), name='unique_constraint'),
        ),
    ]
