# Generated by Django 5.1.1 on 2025-01-14 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0007_alter_route_options_alter_routetrip_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routetrip',
            options={'verbose_name': 'Связь маршрута с поездкой', 'verbose_name_plural': 'Связи маршрутов с поездками'},
        ),
        migrations.RemoveConstraint(
            model_name='route',
            name='unique_constraint',
        ),
        migrations.AddField(
            model_name='trip',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='trip',
            name='price_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общая стоимость'),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(verbose_name='Описание маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='route',
            name='thumbnail',
            field=models.URLField(blank=True, null=True, verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='formed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='owner',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('FORMED', 'Сформировано'), ('DELETED', 'Удалено'), ('FINISHED', 'Завершено'), ('DISMISSED', 'Отклонено')], default='DRAFT', max_length=32, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('origin', 'destination', 'description'), name='unique constraint'),
        ),
    ]
