# Generated by Django 5.1.1 on 2025-01-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0009_alter_routetrip_options_remove_trip_price_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Общее время поездки (минуты)'),
        ),
    ]
