# Generated by Django 5.1.1 on 2025-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0010_trip_duration_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название заявки'),
        ),
    ]
