# Generated by Django 5.1.1 on 2025-01-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0011_alter_trip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='qr',
            field=models.TextField(blank=True, null=True, verbose_name='QR-код'),
        ),
    ]
