# Generated by Django 5.1.1 on 2025-01-30 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0012_trip_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название атрибута')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание атрибута')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
                'db_table': 'attributes',
            },
        ),
        migrations.CreateModel(
            name='RouteAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение атрибута')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_values', to='metroapp.attribute', verbose_name='Атрибут')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='metroapp.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Значение атрибута маршрута',
                'verbose_name_plural': 'Значения атрибутов маршрутов',
                'db_table': 'route_attribute_values',
                'constraints': [models.UniqueConstraint(fields=('route', 'attribute'), name='unique_route_attribute')],
            },
        ),
    ]
