# Generated by Django 5.1.1 on 2025-01-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0013_attribute_routeattributevalue'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='route',
            name='unique constraint',
        ),
        migrations.RemoveField(
            model_name='route',
            name='description',
        ),
        migrations.RemoveField(
            model_name='route',
            name='price',
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('origin', 'destination'), name='unique constraint'),
        ),
    ]
