# Generated by Django 5.1.1 on 2025-01-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0014_remove_route_unique_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание маршрута'),
        ),
        migrations.AddField(
            model_name='route',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
