# Generated by Django 5.1.1 on 2025-01-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0015_route_description_route_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(verbose_name='Описание маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
